core:
    resource: "@FrontasticCommonCoreBundle/Resources/config/routing.xml"
    prefix:   /

frontend:
    resource: "@FrontasticCatwalkFrontendBundle/Resources/config/routing.xml"
    prefix:   /

cart_api:
    resource: "@FrontasticCommonCartApiBundle/Resources/config/routing.xml"
    prefix:   /api/cart

wishlist_api:
    resource: "@FrontasticCommonWishlistApiBundle/Resources/config/routing.xml"
    prefix:   /api/cart

product_api:
    resource: "@FrontasticCommonProductApiBundle/Resources/config/routing.xml"
    prefix:   /api/product

project_api:
    resource: "@FrontasticCommonProjectApiBundle/Resources/config/routing.xml"
    prefix:   /api/project

account_core:
    resource: "@FrontasticCommonAccountApiBundle/Resources/config/routing.xml"
    prefix:   /api/account

api_core:
    resource: "@FrontasticCatwalkApiCoreBundle/Resources/config/routing.xml"
    prefix:   /

dev_vm:
    resource: "@FrontasticCatwalkDevVmBundle/Resources/config/routing.xml"
    prefix:   /

# This should always be the last entry
frontend_nodes:
    resource: .
    prefix:   /
    type:     "frontastic"
